kafkaConfig:
  username: admin
  password: admin
  protocol: SASL_PLAINTEXT
  mechanisms: PLAIN
  clientid: GO-CLIENT-MESSAGE
  brokers1: localhost:9091
  brokers2: localhost:9092
  brokers3: localhost:9093
  groupid: GROUP-01
  topic: NOVO_PEDIDO_77
  partition: 4
  replicationfactor: 3
  lag: 0
  lagcommit: 10