apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-kafka-producer
  namespace: test-a
  labels:
    app: "go-kafka-producer"
    version: "1.0"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: go-kafka-producer
  template:
    metadata:
      labels:
        app: "go-kafka-producer"
        version: "1.0"
    spec:
      containers:
      - name: go-kafka-producer
        image: 908671954593.dkr.ecr.us-east-2.amazonaws.com/go_kafka_producer:latest
        resources:
           requests:
             cpu: 50m
             memory: 64Mi
           limits:
             cpu: 50m
             memory: 64Mi
        ports:
        - containerPort: 9096
        envFrom:
          - configMapRef:
              name: go-kafka-confluentic
      terminationGracePeriodSeconds: 60
