apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: msk-consumer-scaler
  namespace: test-b
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: go-msk-consumer
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: External
    external:
      metricName: metric-msk-topic-length
      targetAverageValue: 40